"""Test Alembic migrations apply cleanly and are reversible.

QA-REG-003: Regression check - migrations are consistent
"""
import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory


class TestAlembicMigrations:
    """Ensure Alembic migration chain is valid and applies cleanly."""

    def test_migration_chain_is_consistent(self):
        """Verify migration chain has no gaps or circular dependencies."""
        cfg = Config("alembic.ini")
        script = ScriptDirectory.from_config(cfg)
        
        # Get all revisions
        revisions = list(script.walk_revisions())
        
        # Should have at least the initial migration
        assert len(revisions) >= 1, "No migrations found"
        
        # Verify each revision has valid downgrade (except base)
        for rev in revisions:
            if rev.down_revision is not None:
                # Downgrade revision should exist
                assert script.get_revision(rev.down_revision) is not None, \
                    f"Revision {rev.revision} references missing down_revision"

    def test_revision_006_downgrade_is_valid(self):
        """Verify migration 006 has a valid downgrade path.
        
        This is a regression test for the duplicate index bug.
        We verify the downgrade script references indexes that actually exist.
        """
        cfg = Config("alembic.ini")
        script = ScriptDirectory.from_config(cfg)
        
        # Get revision 006
        rev = script.get_revision("006")
        assert rev is not None, "Revision 006 not found"
        
        # Read the migration file to check for issues
        import ast
        with open(rev.path, 'r') as f:
            content = f.read()
        
        # Parse the AST
        tree = ast.parse(content)
        
        # Find the downgrade function
        downgrade_func = None
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == 'downgrade':
                downgrade_func = node
                break
        
        assert downgrade_func is not None, "downgrade() function not found"
        
        # Extract all drop_index calls
        drop_indexes = []
        for node in ast.walk(downgrade_func):
            if isinstance(node, ast.Call):
                # Check if it's op.drop_index
                if isinstance(node.func, ast.Attribute) and node.func.attr == 'drop_index':
                    # Get the first argument (index name)
                    if node.args and isinstance(node.args[0], ast.Constant):
                        drop_indexes.append(node.args[0].value)
        
        # The downgrade should only drop manually created indexes
        # Auto-generated indexes from index=True are dropped automatically with the table
        manually_created_indexes = [
            'ix_system_logs_severity_created_at',
            'ix_system_logs_source',
        ]
        
        for idx in manually_created_indexes:
            assert idx in drop_indexes, \
                f" downgrade() should drop manually created index '{idx}'"

    def test_revision_006_no_manual_severity_index(self):
        """Verify migration 006 doesn't manually create ix_system_logs_severity.
        
        This index is auto-generated by index=True on the severity column.
        Manual creation causes DuplicateTableError.
        """
        cfg = Config("alembic.ini")
        script = ScriptDirectory.from_config(cfg)
        
        rev = script.get_revision("006")
        assert rev is not None, "Revision 006 not found"
        
        import ast
        with open(rev.path, 'r') as f:
            content = f.read()
        
        tree = ast.parse(content)
        
        # Find the upgrade function
        upgrade_func = None
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == 'upgrade':
                upgrade_func = node
                break
        
        assert upgrade_func is not None, "upgrade() function not found"
        
        # Check that there's no manual create_index for severity or created_at
        for node in ast.walk(upgrade_func):
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Attribute) and node.func.attr == 'create_index':
                    # Get the first argument (index name)
                    if node.args and isinstance(node.args[0], ast.Constant):
                        idx_name = node.args[0].value
                        assert idx_name not in ['ix_system_logs_severity', 'ix_system_logs_created_at'], \
                            f"Migration 006 manually creates '{idx_name}' which conflicts with index=True on column"

    def test_all_migrations_have_downgrade(self):
        """Verify every migration has a downgrade function."""
        cfg = Config("alembic.ini")
        script = ScriptDirectory.from_config(cfg)
        
        revisions = list(script.walk_revisions())
        
        for rev in revisions:
            # Read the migration file
            import ast
            with open(rev.path, 'r') as f:
                content = f.read()
            
            tree = ast.parse(content)
            
            # Check for downgrade function
            has_downgrade = any(
                isinstance(node, ast.FunctionDef) and node.name == 'downgrade'
                for node in ast.walk(tree)
            )
            
            assert has_downgrade, f"Revision {rev.revision} missing downgrade() function"

    def test_no_broken_revision_references(self):
        """Verify no revision references a non-existent down_revision."""
        cfg = Config("alembic.ini")
        script = ScriptDirectory.from_config(cfg)
        
        all_revisions = {rev.revision: rev for rev in script.walk_revisions()}
        
        for rev in all_revisions.values():
            if rev.down_revision is not None:
                # down_revision can be a string or tuple (for merge points)
                if isinstance(rev.down_revision, str):
                    assert rev.down_revision in all_revisions, \
                        f"Revision {rev.revision} references missing down_revision: {rev.down_revision}"
                elif isinstance(rev.down_revision, (list, tuple)):
                    for dep in rev.down_revision:
                        assert dep in all_revisions, \
                            f"Revision {rev.revision} references missing down_revision: {dep}"
